#!/usr/bin/env python3
import os
import sys
from pathlib import Path
from datetime import datetime

PROJECT_TYPES = {
    "fastapi": {
        "indicators": ["main.py", "requirements.txt"],
        "commands": {
            "install": "pip install -r requirements.txt",
            "dev": "uvicorn src.main:app --reload",
            "test": "pytest tests/"
        }
    },
    "nextjs": {
        "indicators": ["package.json", "next.config.js"],
        "commands": {
            "install": "npm install",
            "dev": "npm run dev",
            "build": "npm run build"
        }
    }
}

def detect_project_type(project_path):
    for ptype, config in PROJECT_TYPES.items():
        for indicator in config["indicators"]:
            if (project_path / indicator).exists():
                return ptype
    return "fullstack"

def generate_agents_md(project_path, project_type=None):
    project_path = Path(project_path)
    if not project_path.exists():
        print(f"✗ Project path not found: {project_path}")
        sys.exit(1)
    
    if project_type is None:
        project_type = detect_project_type(project_path)
    
    content = f"""# {project_path.name}

AI Agent Instructions - Generated by agents-md-gen

## Project Type: {project_type.upper()}

## Key Commands
"""
    
    config = PROJECT_TYPES.get(project_type, {})
    for cmd_name, cmd in config.get("commands", {}).items():
        content += f"- **{cmd_name}**: `{cmd}`\n"
    
    content += f"\n---\n*Generated on {datetime.now().strftime('%Y-%m-%d')}*\n"
    
    output_path = project_path / "AGENTS.md"
    output_path.write_text(content)
    print(f"✓ AGENTS.md created at: {output_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_agents_md.py <project_path> [project_type]")
        sys.exit(1)
    generate_agents_md(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
